"""control_miga_type

Revision ID: 3ed60bb8446a
Revises: 76bfe45b1443
Create Date: 2026-01-18 16:01:47.430280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3ed60bb8446a'
down_revision: Union[str, Sequence[str], None] = '76bfe45b1443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('control_tara', 'is_principal',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('control_tara', 'is_principal',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    # ### end Alembic commands ###
