"""add_column_created_updated

Revision ID: 5ed8f628699f
Revises: 30b5eaf8cdc0
Create Date: 2026-01-27 18:09:07.527110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed8f628699f'
down_revision: Union[str, Sequence[str], None] = '30b5eaf8cdc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_miga', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('control_miga', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_miga', 'updated_at')
    op.drop_column('control_miga', 'created_at')
    # ### end Alembic commands ###
