"""add is_principal to control_tara

Revision ID: 76bfe45b1443
Revises: d85ac512a3e7
Create Date: 2026-01-16 11:34:26.225346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bfe45b1443'
down_revision: Union[str, Sequence[str], None] = 'd85ac512a3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_tara', sa.Column('is_principal', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_tara', 'is_principal')
    # ### end Alembic commands ###
