"""control_tara

Revision ID: 78f3e3d9dfbf
Revises: cc6439fbf69f
Create Date: 2025-12-09 12:32:13.292166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f3e3d9dfbf'
down_revision: Union[str, Sequence[str], None] = 'cc6439fbf69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permisos_modulo', 'modulo',
               existing_type=sa.VARCHAR(length=17, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('CONFIGURACION', 'USUARIOS', 'ROLES', 'MARCACION', 'MOVIMIENTOS', 'AUDITORIA', 'PRODUCCION_LINEAS', 'LINEA_UNO', 'LINEA_DOS', 'LINEA_TRES', 'LINEA_CUATRO', 'LINEA_CINCO', 'LINEA_SEIS', 'CONTROL_TARA', 'CONTROL_PANZA', 'ADMINISTRACION', 'AREA_OPERARIOS', 'CONTROL_LOTE', 'ESPECIES', 'LINEAS_OPERARIOS', 'PLANIFICACION_TURNO', name='moduloenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permisos_modulo', 'modulo',
               existing_type=sa.Enum('CONFIGURACION', 'USUARIOS', 'ROLES', 'MARCACION', 'MOVIMIENTOS', 'AUDITORIA', 'PRODUCCION_LINEAS', 'LINEA_UNO', 'LINEA_DOS', 'LINEA_TRES', 'LINEA_CUATRO', 'LINEA_CINCO', 'LINEA_SEIS', 'CONTROL_TARA', 'CONTROL_PANZA', 'ADMINISTRACION', 'AREA_OPERARIOS', 'CONTROL_LOTE', 'ESPECIES', 'LINEAS_OPERARIOS', 'PLANIFICACION_TURNO', name='moduloenum'),
               type_=sa.VARCHAR(length=17, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
