"""control_miga

Revision ID: bfe86c401b8f
Revises: 4d8b72f8a46d
Create Date: 2026-01-12 17:40:14.553185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe86c401b8f'
down_revision: Union[str, Sequence[str], None] = '4d8b72f8a46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_miga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linea', sa.Integer(), nullable=False),
    sa.Column('registro', sa.Integer(), nullable=False),
    sa.Column('p_miga', sa.Float(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_miga')
    # ### end Alembic commands ###
