"""migration002

Revision ID: cc6439fbf69f
Revises: 7149415b7d72
Create Date: 2025-12-03 19:58:02.719501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'cc6439fbf69f'
down_revision: Union[str, Sequence[str], None] = '7149415b7d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_tara', sa.Column('nombre', sa.String(length=100), nullable=False))
    op.add_column('control_tara', sa.Column('descripcion', sa.String(length=255), nullable=True))
    op.alter_column('control_tara', 'peso_kg',
               existing_type=sa.FLOAT(precision=53),
               nullable=False)
    op.alter_column('control_tara', 'is_active',
               existing_type=mssql.BIT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('control_tara', 'is_active',
               existing_type=mssql.BIT(),
               nullable=False)
    op.alter_column('control_tara', 'peso_kg',
               existing_type=sa.FLOAT(precision=53),
               nullable=True)
    op.drop_column('control_tara', 'descripcion')
    op.drop_column('control_tara', 'nombre')
    # ### end Alembic commands ###
