"""control_panza_entradas

Revision ID: d85ac512a3e7
Revises: bfe86c401b8f
Create Date: 2026-01-14 11:40:13.489255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85ac512a3e7'
down_revision: Union[str, Sequence[str], None] = 'bfe86c401b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permisos_modulo', 'modulo',
               existing_type=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               type_=sa.Enum('CONFIGURACION', 'USUARIOS', 'ROLES', 'MARCACION', 'MOVIMIENTOS', 'AUDITORIA', 'PRODUCCION_LINEAS', 'LINEA_UNO', 'LINEA_DOS', 'LINEA_TRES', 'LINEA_CUATRO', 'LINEA_CINCO', 'LINEA_SEIS', 'CONTROL_TARA', 'CONTROL_PANZA', 'CONTROL_PANZA_ENTRADAS', 'ADMINISTRACION', 'AREA_OPERARIOS', 'CONTROL_LOTE', 'ESPECIES', 'LINEAS_OPERARIOS', 'PLANIFICACION_TURNO', 'DETALLE_PRODUCCION', 'CONTROL_LOTE_SALIDAS', name='moduloenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permisos_modulo', 'modulo',
               existing_type=sa.Enum('CONFIGURACION', 'USUARIOS', 'ROLES', 'MARCACION', 'MOVIMIENTOS', 'AUDITORIA', 'PRODUCCION_LINEAS', 'LINEA_UNO', 'LINEA_DOS', 'LINEA_TRES', 'LINEA_CUATRO', 'LINEA_CINCO', 'LINEA_SEIS', 'CONTROL_TARA', 'CONTROL_PANZA', 'CONTROL_PANZA_ENTRADAS', 'ADMINISTRACION', 'AREA_OPERARIOS', 'CONTROL_LOTE', 'ESPECIES', 'LINEAS_OPERARIOS', 'PLANIFICACION_TURNO', 'DETALLE_PRODUCCION', 'CONTROL_LOTE_SALIDAS', name='moduloenum'),
               type_=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
